name: jira
description: A client to access the Jira Cloud platform using the REST API v3
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  build_runner:
  dart_style:
  json_annotation:
  json_serializable:
  pedantic:
  test:

dependency_overrides:
  dart_style: ^2.0.0